# Generated by Django 3.2.23 on 2023-11-17 18:51

import os
from django.db import migrations

def generate_superuser(apps, schema_editor):
    USERNAME = os.getenv("ADMIN_USERNAME")
    PASSWORD = os.getenv("ADMIN_PASSWORD")
    EMAIL = os.getenv("ADMIN_EMAIL")

    if not USERNAME:
        return

    User = apps.get_model('base', 'User')

    if not User.objects.filter(username=USERNAME, email=EMAIL).exists():
        from django.contrib.auth.hashers import make_password
        User.objects.create(
            username=USERNAME,
            email=EMAIL,
            password=make_password(PASSWORD),
            is_staff=True,
            is_superuser=True
        )



class Migration(migrations.Migration):
    dependencies = [
        ('base', '0001_squashed_0010_auto_20231114_1926'),
    ]
    operations = [migrations.RunPython(generate_superuser)]