# Generated by Django 3.2.23 on 2023-11-18 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20231118_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='follow',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.follow'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='repost',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.post'),
        ),
    ]
