# Generated by Django 3.2.23 on 2023-11-13 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_user_is_private'),
    ]


    operations = [
    migrations.RunSQL('SET CONSTRAINTS ALL IMMEDIATE;'),
        migrations.AddField(
            model_name='post',
            name='category_old',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='base.postcategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('', 'none'), ('ART', 'Art'), ('LIFE', 'Life'), ('PLACES', 'Places'), ('STUFF', 'Stuff')], default='', max_length=50, verbose_name='Category'),
        ),
    migrations.RunSQL('SET CONSTRAINTS ALL DEFERRED;'),
    ]
