# Generated by Django 3.2.23 on 2023-11-18 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20231118_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='follow',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.follow'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='repost',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.post'),
        ),
    ]
