# Generated by Django 3.2.23 on 2023-11-14 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20231113_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reposted_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('ART', 'Art'), ('LIFE', 'Life'), ('PLACES', 'Places'), ('STUFF', 'Stuff')], default='LIFE', max_length=50, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reposts', to=settings.AUTH_USER_MODEL),
        ),
    ]
