# Generated by Django 3.2.23 on 2023-11-18 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20231118_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='saved_post',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_post_activity', to='base.savedpost'),
        ),
    ]
