# Generated by Django 3.2.23 on 2023-11-14 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20231114_0356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='reposted_from',
            new_name='original_post',
        ),
    ]
