# Generated by Django 3.2.23 on 2023-11-22 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_activity_saved_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('ART', 'culture'), ('LIFE', 'life'), ('PLACES', 'places'), ('STUFF', 'stuff')], default='LIFE', max_length=50, verbose_name='Category'),
        ),
    ]
