# Generated by Django 3.2.23 on 2023-11-14 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20231114_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category_old',
        ),
        migrations.DeleteModel(
            name='PostCategory',
        ),
    ]
