# Generated by Django 3.2.23 on 2023-11-14 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20231114_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='from_user',
        ),
        migrations.AlterField(
            model_name='post',
            name='original_post',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='base.post'),
        ),
    ]
