# Generated by Django 3.2.23 on 2023-11-22 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followrequest',
            name='is_approved',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
