# Generated by Django 3.2.23 on 2023-12-27 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('item_type', models.CharField(choices=[('MOVIE', 'movie'), ('BOOK', 'book'), ('TV', 'tv'), ('MUSIC', 'music'), ('CONCERT', 'concert')], default='MOVIE', max_length=50, verbose_name='Type')),
                ('note', models.TextField(max_length=250)),
                ('review', models.TextField(max_length=250)),
                ('rating', models.IntegerField(choices=[(1, 'hated'), (2, 'disliked'), (3, 'liked'), (4, 'loved')])),
                ('started_date', models.DateField(blank=True, null=True)),
                ('ended_date', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'backlog'), (2, 'in progress'), (3, 'completed'), (4, 'abandoned')])),
                ('original_item', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='base.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
