# Generated by Django 3.2.23 on 2023-12-27 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='note',
            field=models.TextField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, 'hated'), (2, 'disliked'), (3, 'liked'), (4, 'loved')], null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='review',
            field=models.TextField(blank=True, default='', max_length=250, null=True),
        ),
    ]
