# Generated by Django 3.2.23 on 2023-12-29 20:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_auto_20231227_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='last_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('MOVIE', 'movie'), ('BOOK', 'book'), ('TV', 'tv'), ('MUSIC', 'music'), ('EVENT', 'event')], default='MOVIE', max_length=50, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.IntegerField(choices=[(1, 'later'), (2, 'now'), (3, 'finished'), (4, 'quit')], default=1),
        ),
    ]
