# Generated by Django 3.2.23 on 2024-01-01 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_itemlist_is_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemlist',
            options={'ordering': ['-is_default', '-created']},
        ),
    ]
