# Generated by Django 3.2.23 on 2024-01-04 04:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('MOVIE', 'movie'), ('BOOK', 'book'), ('TV', 'tv'), ('LIFE', 'life')], default='MOVIE', max_length=50, verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='ItemLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked', to='base.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to=settings.AUTH_USER_MODEL, verbose_name='Like By')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
