# Generated by Django 3.2.23 on 2024-01-06 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_item_hide_from_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='like_item',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_item_activity', to='base.itemlike'),
        ),
        migrations.AddField(
            model_name='activity',
            name='mention_item',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mention_item_activity', to='base.item'),
        ),
        migrations.AddField(
            model_name='activity',
            name='save_item',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='save_item_activity', to='base.item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
    ]
