# Generated by Django 3.2.23 on 2024-01-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_auto_20240105_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='author',
            field=models.TextField(blank=True, default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=75),
        ),
    ]
