# Generated by Django 3.2.23 on 2024-01-18 17:53

from django.db import migrations, models

def move_reviews(apps, schema_editor):
    Item = apps.get_model('base', 'Item')

    for item in Item.objects.all():
        if item.review:
            item.note = item.review 
            item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_alter_item_author'),
    ]

    operations = [
        migrations.RunPython(move_reviews),
    ]
