# Generated by Django 3.2.23 on 2024-01-21 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_move_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='review',
        ),
    ]
