# Generated by Django 3.2.23 on 2024-01-22 17:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_remove_item_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tag', models.CharField(max_length=40)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged', to='base.item')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
