# Generated by Django 3.2.23 on 2024-01-26 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='action',
            field=models.TextField(blank=True, default='', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='comment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_item_activity', to='base.comment'),
        ),
        migrations.AddField(
            model_name='activity',
            name='item',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_activity', to='base.item'),
        ),
    ]
