# Generated by Django 3.2.23 on 2024-01-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_auto_20240126_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='action',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
    ]
