# Generated by Django 3.2.23 on 2024-01-26 18:39

from django.db import migrations, models
import django.db.models.deletion
from django.db.models import F


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_alter_activity_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='item_like',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_likst_activity', to='base.itemlike'),
        ),
    ]
