# Generated by Django 3.2.23 on 2024-02-06 23:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_move_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='last_status',
            field=models.IntegerField(choices=[(1, 'later'), (2, 'now'), (3, 'finished'), (4, 'quit')], default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='last_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
