# Generated by Django 3.2.23 on 2024-02-07 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_auto_20240206_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='original_post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.RemoveField(
            model_name='savedpost',
            name='post',
        ),
        migrations.RemoveField(
            model_name='savedpost',
            name='user',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='like_item',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='mention',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='mention_item',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='repost',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='save_item',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='saved_post',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_list',
        ),
        migrations.DeleteModel(
            name='ItemList',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='SavedPost',
        ),
    ]
