# Generated by Django 3.2.23 on 2024-02-09 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_auto_20240206_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('MOVIE', 'movie'), ('BOOK', 'book'), ('TV', 'tv'), ('FOOD', 'food'), ('LIFE', 'life')], default='MOVIE', max_length=50, verbose_name='Type'),
        ),
    ]
