# Generated by Django 3.2.24 on 2024-02-19 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_alter_item_item_type'),
        ('authtoken','0003_tokenproxy')
    ]

    operations = [
    ]
