# Generated by Django 3.2.24 on 2024-03-17 02:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_auto_20240218_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppleSS0',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('email', models.CharField(max_length=80)),
                ('apple_id', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
