# Generated by Django 3.2.24 on 2024-03-17 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_appless0'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppleSS0',
            new_name='AppleSSO',
        ),
    ]
