# Generated by Django 3.2.25 on 2024-03-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_alter_demofolder_shared_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='demodemo',
            name='file_extension',
            field=models.CharField(default='mp3', max_length=4),
        ),
    ]
