# Generated by Django 3.2.25 on 2024-03-23 20:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_demodemo_file_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='demodemo',
            name='source_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
