# Generated by Django 3.2.25 on 2024-03-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0048_demodemo_source_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demodemo',
            name='source_created',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
