# Generated by Django 3.2.25 on 2024-03-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0049_alter_demodemo_source_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='demosong',
            name='priority_as_of',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
