# Generated by Django 3.2.25 on 2024-03-31 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_demosong_priority_as_of'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(max_length=250)),
                ('timestamp', models.IntegerField(blank=True, null=True)),
                ('demo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='base.demodemo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_comments', to=settings.AUTH_USER_MODEL, verbose_name='commenter')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
