# Generated by Django 3.2.25 on 2024-04-01 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0052_rename_body_democomment_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='democomment',
            old_name='comment',
            new_name='body',
        ),
    ]
