# Generated by Django 3.2.25 on 2024-04-03 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0054_auto_20240402_1728'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DemoShareKeys',
            new_name='DemoShareKey',
        ),
    ]
