# Generated by Django 3.2.25 on 2024-04-04 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0055_rename_demosharekeys_demosharekey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('MOVIE', 'WATCH'), ('BOOK', 'READ'), ('TV', 'WATCH'), ('LISTEN', 'LISTEN'), ('FOOD', 'EAT'), ('LIFE', 'VIBE')], default='MOVIE', max_length=50, verbose_name='Type'),
        ),
    ]
