# Generated by Django 3.2.25 on 2024-04-04 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_alter_item_item_type'),
    ]

    def set_item_type(apps, schema_editor):
        Item = apps.get_model("base", "Item")

        items = Item.objects.all()
        for item in items:
            if item.item_type == "MOVIE":
                item.item_type2 = "WATCH"
            elif item.item_type ==  "TV":
                item.item_type2 = "WATCH"
            elif item.item_type ==  "BOOK":
                item.item_type2 = "READ"
            elif item.item_type ==  "FOOD":
                item.item_type2 = "EAT"
            elif item.item_type ==  "LIFE":
                item.item_type2 = "VIBE"
            item.save()


    operations = [
        migrations.AddField(
            model_name='item',
            name='item_type2',
            field=models.CharField(blank=True, choices=[('WATCH', 'watch'), ('READ', 'read'), ('LISTEN', 'listen'), ('EAT', 'eat'), ('VIBE', 'vibe')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('MOVIE', 'movie'), ('BOOK', 'book'), ('TV', 'tv'), ('FOOD', 'food'), ('LIFE', 'life')], default='MOVIE', max_length=50, verbose_name='Type'),
        ),
        migrations.RunPython(set_item_type)
        ,
    ]
