# Generated by Django 3.2.25 on 2024-04-04 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0057_auto_20240403_1746'),
    ]

    def set_item_type(apps, schema_editor):
        Item = apps.get_model("base", "Item")

        items = Item.objects.all()
        for item in items:
            if item.item_type == "MOVIE":
                item.item_type = "WATCH"
            elif item.item_type ==  "TV":
                item.item_type = "WATCH"
            elif item.item_type ==  "BOOK":
                item.item_type = "READ"
            elif item.item_type ==  "FOOD":
                item.item_type = "EAT"
            elif item.item_type ==  "LIFE":
                item.item_type = "MISC"
            item.save()

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_type2',
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('WATCH', 'watch'), ('READ', 'read'), ('EAT', 'eat'), ('LISTEN', 'listen'), ('MISC', 'misc'), ('BOOK', 'x'), ('FOOD', 'x'), ('LIFE', 'x'), ('MOVIE', 'x'), ('TV', 'x')], default='WATCH', max_length=50, verbose_name='Type'),
        ),
        migrations.RunPython(set_item_type)
        ,
    ]
