# Generated by Django 3.2.25 on 2024-04-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0058_auto_20240403_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='demofolder',
            name='key',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
