# Generated by Django 3.2.25 on 2024-04-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0061_block_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hide_objectionable_content',
            field=models.BooleanField(default=False),
        ),
    ]
