# Generated by Django 3.2.25 on 2024-04-26 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0062_user_hide_objectionable_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='ended_date',
        ),
        migrations.RemoveField(
            model_name='item',
            name='started_date',
        ),
    ]
