# Generated by Django 3.2.25 on 2024-05-02 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0064_adminmessage_usermessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_feed_call',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
