# Generated by Django 3.2.25 on 2024-12-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0066_auto_20240602_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demodemo',
            options={'ordering': ['-source_created']},
        ),
        migrations.AlterModelOptions(
            name='demofolder',
            options={'ordering': ['-latest_demo']},
        ),
        migrations.AlterModelOptions(
            name='demosong',
            options={'ordering': ['-latest_demo']},
        ),
        migrations.AddField(
            model_name='demofolder',
            name='latest_demo',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='demosong',
            name='latest_demo',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
