# Generated by Django 3.2.25 on 2025-06-03 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0067_auto_20241229_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='MansionsAlbum',
            fields=[
                ('slug', models.SlugField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cover_art', models.ImageField(blank=True, null=True, upload_to='albums/covers/')),
                ('summary', models.CharField(blank=True, max_length=1000, null=True)),
                ('credits', models.CharField(blank=True, max_length=1000, null=True)),
                ('release_notes', models.CharField(blank=True, max_length=1000, null=True)),
                ('lyrics', models.CharField(blank=True, max_length=10000, null=True)),
            ],
            options={
                'ordering': ['-release_date'],
            },
        ),
    ]
