# Generated by Django 3.2.25 on 2025-06-03 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0068_mansionsalbum'),
    ]

    operations = [
        migrations.AddField(
            model_name='mansionsalbum',
            name='album_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
