# Generated by Django 3.2.25 on 2025-06-03 01:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0069_mansionsalbum_album_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MansionsShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(max_length=200)),
                ('show_date', models.DateField()),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=2)),
                ('other_acts', models.CharField(blank=True, max_length=200, null=True)),
                ('show_type', models.CharField(max_length=2)),
                ('note', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['-show_date'],
            },
        ),
        migrations.AlterField(
            model_name='mansionsalbum',
            name='credits',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mansionsalbum',
            name='lyrics',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mansionsalbum',
            name='release_notes',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mansionsalbum',
            name='summary',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
