# Generated by Django 3.2.25 on 2025-06-03 01:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0070_auto_20250602_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='mansionsalbum',
            name='making_of',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
