# Generated by Django 3.2.25 on 2025-06-06 22:13

from django.db import migrations
import csv
from datetime import datetime
from django.utils.text import slugify
import os

def load_show_data(apps, schema_editor):
    MansionsShow = apps.get_model('base', 'MansionsShow')
    base_dir = os.path.dirname(__file__)
    csv_path = os.path.join(base_dir, 'seed_data', 'show_archive.csv')

    with open(csv_path, newline='', encoding='utf-8') as f:
        reader = csv.DictReader(f, quotechar='"')  # this is the key line
        for row in reader:
            MansionsShow.objects.create(
                venue=row['venue'],
                show_date=datetime.strptime(row['date'], '%Y-%m-%d').date(),
                city=row['city'],
                state=row['state'],
                other_acts=row.get('other_acts', '') or None,
                show_type=row['show_type'],
                note=row.get('note', '') or None
            )
class Migration(migrations.Migration):

    dependencies = [
        ('base', '0073_load_mansions_shows'),
    ]

    operations = [
        migrations.RunPython(load_show_data),
    ]
