# Generated by Django 3.2.25 on 2025-09-01 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0075_auto_20250901_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hand',
            name='current_turn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_hands', to='base.player'),
        ),
    ]
