# Generated by Django 3.2.25 on 2025-09-02 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0076_alter_hand_current_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='hand',
            name='trump_suit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='trick',
            name='lead_suit',
            field=models.CharField(default='spades', max_length=10),
            preserve_default=False,
        ),
    ]
