# Generated by Django 3.2.25 on 2025-09-02 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0077_auto_20250901_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='trick',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tricks_won', to='base.player'),
        ),
    ]
