# Generated by Django 3.2.25 on 2025-09-03 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0079_auto_20250902_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='hand',
            name='num_of_tricks',
            field=models.IntegerField(default=1),
        ),
    ]
