# Generated by Django 3.2.25 on 2025-09-03 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0080_hand_num_of_tricks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='players',
        ),
        migrations.AddField(
            model_name='player',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='base.group'),
        ),
    ]
