# Generated by Django 3.2.25 on 2025-09-04 00:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0081_auto_20250902_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiverGame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='base.group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='hand',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hands', to='base.rivergame'),
        ),
    ]
