# Generated by Django 3.2.25 on 2026-07-01 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0082_auto_20250903_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreativeWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('work_type', models.CharField(choices=[('music', 'Music'), ('painting', 'Painting'), ('coding', 'Coding'), ('other', 'Other')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='completed', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('external_link', models.URLField(blank=True, help_text='Link to Mansions, Rex, etc. or project page', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='creative_works/images/')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='creative_works/audio/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['?'],
            },
        ),
    ]
