# Generated by Django 3.2.25 on 2026-07-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0083_creativework'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
