# Generated by Django 3.2.25 on 2026-07-10 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0084_visitorcounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='creativework',
            name='work_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='creativework',
            name='work_type',
            field=models.CharField(choices=[('music', 'Music'), ('painting', 'Painting'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
