# Generated by Django 3.2.25 on 2026-07-11 17:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0085_auto_20260710_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creativework',
            name='work_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
