# Generated by Django 6.0.7 on 2026-08-01 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0086_alter_creativework_work_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="DaycareBaselineSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_of_week", models.IntegerField(max_length=1)),
                ("chris_location", models.CharField(max_length=10)),
                ("robin_location", models.CharField(max_length=10)),
                ("wakeup", models.CharField(max_length=10)),
                ("dropoff", models.CharField(max_length=10)),
                ("pickup", models.CharField(max_length=10)),
                ("on_call", models.CharField(max_length=10)),
                ("chris_wod", models.CharField(max_length=10)),
                ("robin_wod", models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name="creativework",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="groupplayer",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="hand",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="mansionsshow",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="playerstate",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="trick",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="visitorcounter",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.CreateModel(
            name="DaycareScheduleOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("override_type", models.CharField(max_length=50)),
                ("value", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("date", "override_type"),
                        name="unique_date_override_type",
                    )
                ],
            },
        ),
    ]
