version: "3"
services:
  gumsup4_web:
    image: gumsup4_api_dev:latest
    ports:
      - "8000:8000"
    environment:
      PYTHONUNBUFFERED: "True"
      DJANGO_SETTINGS_MODULE: gumsup4.settings.dev
      DATABASE_URL: postgres://django:django@gumsup4_db:5432/gumsup4
      REDIS_URL: redis://gumsup4_redis:6379/0
    volumes:
      - "${PWD}:/src/app"
    depends_on:
      - gumsup4_db
      - gumsup4_redis
    command:
      gunicorn gumsup4.wsgi --bind 0.0.0.0:8000 --reload
  gumsup4_db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: django
      POSTGRES_USER: django
      POSTGRES_DB: gumsup4
    logging:
      driver: none
  gumsup4_redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    logging:
      driver: none
