# Build + minify frontend assets.
FROM gumsup4_app AS frontend

# Python application container.
FROM python:3.7 AS app

WORKDIR /src/app

ARG REQUIREMENTS=requirements.txt

RUN useradd app && chown -R app:app .

COPY ./requirements.* ./
RUN pip install -r ${REQUIREMENTS}

COPY --chown=app:app . .


USER app

RUN mkdir -p public && python manage.py collectstatic

CMD gunicorn gumsup4.wsgi --bind 0.0.0.0:8000
